version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: django_dx
      POSTGRES_PASSWORD: django_dx
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
       - django_dx_pgdata:/data/postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  django_dx_pgdata: